name: Build Pokered
on:
  issue_comment:
    types: [ edited ]
    comment:
      id: 821124407
    
jobs:  
  build-pokered-girl:
    runs-on: ubuntu-latest
    container:
      image: nogfrog/pokered-build-env
    steps:
      - name: Check out pokered-girl code
        uses: actions/checkout@v2
        with:
          repository: Nog-Frog/pokered-girl
  
      - name: Check out PokeHebrew
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build ROMs
        run: |
          cd pokered-girl
          make

      - name: Replace old ROMs in PokeHebrew
        run: |
          mv -uf pokered-girl/pokered.gbc PokeHebrew/roms/red-girl.gbc
          mv -uf pokered-girl/pokeblue.gbc PokeHebrew/roms/blue-girl.gbc

      - name: commit changes
        id: commit-step
        continue-on-error: true # Don't fail job if there are no changes to commit
        run: |
          cd PokeHebrew
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update girl version roms" -a

      - name: Push changes
        if: ${{ steps.commit-step.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master